DATA:
  IMG_SIZE: 448
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window12_384_finetune
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
